### ISSUE TITLE
Link paths get confused in certain scenarios when deploying on github.io

### ISSUE THREAD

**Issue by QuintyHH** [marianzburlea/pug-starter#72]
Deploy to github.io is still wonky if, for example, ur menu is generated from a json and it has both internal (ex: /about-me) links and external (ex: youtube) links

**Comment by QuintyHH** [comment]
A quick workaround is to add a "isExternal" prop to the json objects, and format the url depending on it's state ... ex: 
``` 
if item.external == "yes"
    a.header__menu-link(href=item.href, target=item.target)=item.text
else
     a.header__menu-link(href=`${baseUrl}`+item.href, target=item.target)=item.text

**Comment by QuintyHH** [comment]
Another way of fixing this is to parse the json's "href" property and if it starts with a "http:" or something of the sort, do a similar If state check as above

**Comment by marianzburlea** [comment]
It seems it's not a problem, just a logical decision.
